insert into user_role(role, description) VALUES("ROLE_USER", "default role for user");
insert into user_role(role, description) VALUES("ROLE_ADMIN", "default role for admin");
insert into user_profile(firstname, lastname, gender, birthday) VALUES("Michał", "Wiśniewski", 1, '1990-01-03');
insert into user(email, password, user_profile_id) VALUES("test", "test", 1);
insert into user_roles(user_id, roles_id) VALUES(1, 1);
insert into user_profile(firstname, lastname, gender, birthday) VALUES("ZHP", "hufiec Białystok", 1, '1970-01-01');
insert user(email, password, user_profile_id) VALUES("bialystok@zhp.pl", "test", 2);
insert into user_roles(user_id, roles_id) VALUES(2, 1);
insert into user_profile(firstname, lastname, gender, birthday) VALUES("Scout Association", "London", 1, '1970-01-01');
insert user(email, password, user_profile_id) VALUES("london@scout.uk", "test", 3);
insert into user_roles(user_id, roles_id) VALUES(3, 1);
insert into groups(name) VALUES("hufiec Białystok");
insert into post(content, created_at, groups_id, owner_id, category) VALUES("To jest nasz pierwszy post", "2017-12-01 12:11:10", 1, 2, 1);
insert into post(content, created_at, groups_id, owner_id, category) VALUES("To jest nasz drugi post", "2017-12-01 13:12:11", 1, 2, 1);
insert into post(content, created_at, groups_id, owner_id, category) VALUES("Cześć! Jestem nowy w drużynie.", "2017-12-01 13:12:11", 1, 1, 1);
insert into groups(name) VALUES("scout group London");
insert into post(content, created_at, groups_id, owner_id, category) VALUES("This is our first post", "2017-12-02 14:13:12", 2, 3, 1);
insert into post(content, created_at, groups_id, owner_id, category) VALUES("This is our second post", "2017-12-02 15:14:13", 2, 3, 1);
insert into user_groups(user_profile_id, groups_id) VALUES(1, 1);
insert into user_groups(user_profile_id, groups_id) VALUES(1, 2);
insert into user_wall(user_profile, post, shown) VALUES(1, 1, false);